### PR TITLE
Navigation Drawer added

### PR DESCRIPTION
**Pull request by Vrungel322**
work only Оголошення and Вихiд

### CODE REVIEW

**Comment by floring** [comment]
Thanks, your request is on a consideration.

**Comment by unisol-ua** [comment]
üÔÏ ÏÂÙÞÎÏ  ÎÁÚÙ×ÁÅÔÓÑ "is being reviewed"/"is under review". "consider"  
ÕÐÏÔÒÅÂÑÀÔ × ÓÉÔÕÁÃÉÑÈ ÔÉÐÁ "taken into consideration" = "ÐÒÉÎÑÔÏ Ë  
Ó×ÅÄÅÎÉÀ"/"ÒÁÓÓÍÁÔÒÉ×ÁÅÍ ×ÏÚÍÏÖÎÏÓÔØ"/"ÂÕÄÅÍ ÉÍÅÔØ ××ÉÄÕ".

**Comment by Vrungel322** [comment]
что с этими анимациями и шторкой?

**Comment by floring** [comment]
Sorry, your request cannot be launched. Please, make sure that your build settings are correct.

**Pull request closed without merging**
