### PR TITLE
Use HTTPS protocol

### LINKED ISSUE #39: Use HTTPS API endpoint instead HTTP

### PR DESCRIPTION
**Pull request by ernado-x**
Close #39

### CODE REVIEW

**Comment by unisol-ua** [comment]
Either 2 https backends will be necessary or even fallback to http option - if TLSv1 support gets droppped - https will fail for outdated android versions.

**Comment by ernado-x** [comment]
So it will be reason to update their devices ;)
As I know, this problem is actually only for Android 2.x devices.

**Comment by unisol-ua** [comment]
We already don't support SSLv* - so no support for 2.x devices. If it will be resumed - it'll be a separate dns name, separate certificate.
https://www.ssllabs.com/ssltest/analyze.html?d=api.campus.kpi.ua
TLSv1 off (CBC ciphers off) = devices up to 4.3 will be unable to connect.

I'd propose declaring an array of backends instead of single backend with an option to downgrade to "whatever works" and perhaps notification "using high/medium/low/no encryption".
Also, as its a mobile app - we need to test how encryption affects power draw of the devices and if it's worth using e.g. 128-bit instead of 256-bit encryption (I have no idea how much traffic and requests is generated by typical usage).
In certain cases when we know the data is "public" - we may not use encryption at all.

**Comment by ernado-x** [comment]
Any progress on HTTPS?

**Comment by ernado-x** [comment]
Issue #39  already closed by 87ba079

**Pull request closed without merging**
